import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/AuthProvider";
import LeftBar from "./_components/LeftBar";
import RightBar from "./_components/RightBar";
import { EdgeStoreProvider } from "./edgestore/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <EdgeStoreProvider>
      <AuthProvider>
        
        <body className={inter.className}>
          <div className="w-full h-full flex items-center justify-center">
            <div className="max-w-screen-xl w-full h-full  flex">
              <LeftBar />

                {children}

              <RightBar />
            </div>
          </div>
        </body>
        
      </AuthProvider>
      </EdgeStoreProvider>
    </html>
  );
}
